// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'response.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

BaseResponse _$BaseResponseFromJson(Map<String, dynamic> json) => BaseResponse(
  //? This function is generated by the json_serializable package to convert a JSON map into an instance of the BaseResponse class. The implementation is based on the fields and annotations in the BaseResponse class.
  status: (json['status'] as num?)?.toInt(),
  message: json['message'] as String?,

  //? The _$BaseResponseFromJson function takes a Map<String, dynamic> as input and returns an instance of BaseResponse. It uses the field names and types defined in the BaseResponse class to extract the values from the JSON map and create an instance of the class.
);
Map<String, dynamic> _$BaseResponseToJson(BaseResponse instance) =>
    <String, dynamic>{'status': instance.status, 'message': instance.message};
//? the _$BaseResponseToJson function is generated by the json_serializable package to convert an instance of the BaseResponse class into a JSON map. The implementation is based on the fields and annotations in the BaseResponse class. It takes an instance of BaseResponse as input and returns a Map<String, dynamic> that represents the JSON data for that instance. The keys in the map correspond to the field names defined in the BaseResponse class, and the values are taken from the instance's fields.
UserResponse _$UserResponseFromJson(Map<String, dynamic> json) => UserResponse(
  id: json['id'] as String?,
  name: json['name'] as String?,
  numOfNotifications: (json['numOfNotifications'] as num?)?.toInt(),
);

Map<String, dynamic> _$UserResponseToJson(UserResponse instance) =>
    <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'numOfNotifications': instance.numOfNotifications,
    };

ContactsResponse _$ContactsResponseFromJson(Map<String, dynamic> json) =>
    ContactsResponse(
      number: json['number'] as String?,
      email: json['email'] as String?,
      link: json['link'] as String?,
    );

Map<String, dynamic> _$ContactsResponseToJson(ContactsResponse instance) =>
    <String, dynamic>{
      'number': instance.number,
      'email': instance.email,
      'link': instance.link,
    };

AuthResponse _$AuthResponseFromJson(Map<String, dynamic> json) => AuthResponse(
  //? This function is generated by the json_serializable package to convert a JSON map into an instance of the AuthResponse class. The implementation is based on the fields and annotations in the AuthResponse class.
  //? The _$AuthResponseFromJson function takes a Map<String, dynamic> as input and returns an instance of AuthResponse. It uses the field names and types defined in the AuthResponse class to extract the values from the JSON map and create an instance of the class. For the user and contacts fields, it checks if the corresponding JSON value is null before attempting to create an instance of UserResponse or ContactsResponse, ensuring that it handles null values gracefully.
  //? The user field is extracted from the JSON map and converted into an instance of UserResponse using the fromJson factory constructor. If the user field in the JSON is null, it will be set to null in the AuthResponse instance. The same logic applies to the contacts field, which is converted into an instance of ContactsResponse.
  user: json['user'] == null
      ? null
      : UserResponse.fromJson(json['user'] as Map<String, dynamic>),
  contacts: json['contacts'] == null
      ? null
      : ContactsResponse.fromJson(json['contacts'] as Map<String, dynamic>),
);

Map<String, dynamic> _$AuthResponseToJson(AuthResponse instance) =>
    <String, dynamic>{'user': instance.user, 'contacts': instance.contacts};
//? The _$AuthResponseToJson function is generated by the json_serializable package to convert an instance of the AuthResponse class into a JSON map. The implementation is based on the fields and annotations in the AuthResponse class. It takes an instance of AuthResponse as input and returns a Map<String, dynamic> that represents the JSON data for that instance. The keys in the map correspond to the field names defined in the AuthResponse class, and the values are taken from the instance's fields. For the user and contacts fields, it will automatically call the toJson method on those instances to convert them into JSON maps as well, ensuring that nested objects are properly serialized into JSON format.
