import 'package:dio/dio.dart';
import 'package:retrofit/retrofit.dart';
import 'package:tut_app/app/constants.dart';
import 'package:tut_app/data/response/response.dart';
part 'app_api.g.dart';

@RestApi(baseUrl: Constants.baseUrl)
abstract class AppServiceClient {
  factory AppServiceClient(Dio dio, {String baseUrl}) =
      _AppServiceClient; //* this factory constructor is used to create an instance of the AppServiceClient class. The implementation of this constructor is generated by the retrofit package based on the annotations and method signatures defined in the AppServiceClient class. The generated implementation will handle the HTTP requests and responses according to the defined API endpoints and data models.
  @POST("/users/login") //? This annotation indicates that this method will perform a POST request to the specified endpoint ("/users/login"). The retrofit package uses this annotation to generate the necessary code for making the HTTP request when the login method is called.
  Future<AuthResponse> login(
    //? This method defines the login API endpoint. It takes an email and password as parameters, which are annotated with @Field to indicate that they should be included in the request body as form data. The method returns a Future that resolves to an AuthResponse, which is a data model representing the response from the login API.
    @Field("email") String email,
    @Field("Password") String password,
  );
}

//* what is the benefit of using retrofit package in flutter ?
//1. It provides a simple and declarative way to define API endpoints and their corresponding requests and responses using annotations.
//2. It generates the necessary code for making HTTP requests and handling responses based on the defined API endpoints and data models, which reduces boilerplate code and improves code maintainability.
//3. It supports various HTTP methods (GET, POST, PUT, DELETE, etc.) and allows for easy handling of query parameters, headers, and request bodies, making it easier to work with RESTful APIs in Flutter applications.